import "../styles/global.scss";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body /* className="d-flex flex-column vh-100" */ >
        {/* <Header/>
        <Container className="flex-grow-1"> */}
        {children}
        {/* </Container> */}
       {/*  <Footer/> */}
      </body>
    </html>
  );
}
